VERSION = "1.0"

[DOCUMENTATION]
ORG_NAME = "WhaleHub"
ORG_URL = "https://whalehub.io"
ORG_DESCRIPTION = "WhaleHub is a yield optimization platform that allows users to stake AQUA for boosted rewards by minting BLUB."
ORG_LOGO = "https://cdn.prod.website-files.com/66f99e9619d477e7b42289e7/670e3967c505ca664b04b6d7_Blubber%20white.svg"
ORG_TWITTER = "@whalehubdefi"
ORG_GITHUB = "WhaleHubDev"
ORG_EMAIL = "contact@whalehub.io"

[[CURRENCIES]]
code = "BLUB"
issuer = "GCX6LOZ6ZEXBHLTPOPP2THN74K33LMT4HKSPDTWSLVCF4EWRGXOS7D3V"
display_decimals = 7
name = "Blubber Token"
desc = "BLUB is a liquid derivative version of AQUA, which participates in the liquidity mining of the BLUB-AQUA pair. The WhaleHub reward asset is BLUBBER or BLUB for short."
conditions = "No specific restrictions. Note, BLUB is not redeemable for AQUA."
image = "https://cdn.prod.website-files.com/66f99e9619d477e7b42289e7/670e3967c505ca664b04b6d7_Blubber%20white.svg"
