VERSION = "1.0"

[DOCUMENTATION]
ORG_NAME = "WhaleHub"
ORG_URL = "https://whalehub.io"
ORG_DESCRIPTION = "WhaleHub is a yield optimization platform that allows users to stake AQUA for boosted rewards by minting BLUB."
ORG_LOGO = "https://lavender-armed-termite-130.mypinata.cloud/ipfs/bafkreiciyg3jgwlsrw5m6auwmlwf7yhhxlzofafdwmoo3iimpjdt5nwqha"
ORG_TWITTER = "@whalehubdefi"
ORG_GITHUB = "WhaleHubDev"
ORG_EMAIL = "contact@whalehub.io"

[[CURRENCIES]]
code = "BLUB"
issuer = "GCYITYIOHQIDYK5ASX5CC7LVC4WOTHMCMPNDCTPARUUFHYDV2EBX55IQ"
display_decimals = 7
name = "Blubber Token"
desc = "BLUB is a liquid derivative version of AQUA, which participates in the liquidity mining of the BLUB-AQUA pair. The WhaleHub reward asset is BLUBBER or BLUB for short."
conditions = "No specific restrictions. Note, BLUB is not redeemable for AQUA."
image = "https://lavender-armed-termite-130.mypinata.cloud/ipfs/bafkreiciyg3jgwlsrw5m6auwmlwf7yhhxlzofafdwmoo3iimpjdt5nwqha"
